from nbhelp import md, code, sol, build, PRELUDE

# =============================================================== 01
build("01_first_contact.ipynb", "First Contact", [
md("""
# 01 · First Contact

**Session 1 · Tue Sep 15 · 2 hours**

### Why this notebook exists

By the end of it you will have done the four things you will do in *every* data assignment for the
next eight weeks: load a file, look at its shape, summarise it, and draw one picture. Everything
later in the course is a variation on these four moves.

There is no statistics in this notebook. That is deliberate. Today is about making the tools stop
being in your way.

### How to use a notebook

- Click a grey cell and press **Shift+Enter** to run it. Output appears underneath.
- Cells share memory top to bottom. If something breaks, run from the top again.
- You cannot break anything permanently. The data files are regenerated by `make_data.py`.
"""),
code(PRELUDE),
md("""
That cell imported your tools. In plain English:

| Line | What it gives you |
|---|---|
| `numpy as np` | fast arrays and random numbers |
| `pandas as pd` | spreadsheet-like tables, called *DataFrames* |
| `matplotlib.pyplot as plt` | plotting |
| `seaborn as sns` | prettier plotting, built on matplotlib |
| `rng` | a random number generator with a fixed seed, so your numbers match mine |

`as np` just means "I'll call it `np` from now on" — it saves typing. Nothing deeper.
"""),
md("""
## 1 · Load a file

`pd.read_csv` reads a comma-separated file into a DataFrame. This is the single most-used function in
applied data work.
"""),
code("""
deposits = pd.read_csv(DATA / "branch_deposits.csv")
deposits.head()      # .head() shows the first 5 rows
"""),
md("""
**Read the output as a table.** Each row is one *observation* (here, one account). Each column is one
*variable*. That vocabulary matters — lectures will say "observation" and "variable" constantly, and
they mean row and column.

## 2 · How big is it?
"""),
code("""
print("shape (rows, columns):", deposits.shape)
print("number of rows, n =", len(deposits))
print()
print("column names and types:")
print(deposits.dtypes)
"""),
md("""
`deposits.shape` gives `(1200, 5)` — 1,200 rows and 5 columns.

**That first number is `n`.** When a lecture writes `n = 1200`, this is what it means: how many
observations you have. You will see `n` in almost every formula in this course, and it is never more
complicated than "how many rows."

## 3 · Summarise it
"""),
code("""
deposits.describe()
"""),
md("""
This is your first real statistical output, so let's decode every row of it:

| Row | Meaning | Notation |
|---|---|---|
| `count` | how many non-missing values | `n` |
| `mean` | the average | `x̄` ("x-bar") |
| `std` | standard deviation — typical distance from the mean | `s` or `σ` |
| `min` / `max` | smallest and largest |  |
| `25%` / `50%` / `75%` | quartiles; `50%` is the **median** |  |

Now look hard at the `balance` column, and compare `mean` with `50%` (the median).
"""),
code("""
print(f"mean balance:   ${deposits.balance.mean():>10,.0f}")
print(f"median balance: ${deposits.balance.median():>10,.0f}")
print(f"the mean is {deposits.balance.mean() / deposits.balance.median():.1f}x the median")
"""),
md("""
### Stop and think about that

The mean is about six times the median. Both are called "the average" in everyday speech, and here
they disagree by a factor of six.

That is not a bug in the data. It is the most important practical fact in descriptive statistics: **a
few very large values drag the mean but barely move the median.** A handful of private-banking
clients with very large balances pull the mean upward; the median just asks "what does the account in
the middle look like?" and ignores them.

This is why "average balance" is a nearly useless phrase in a bank without saying which average, and
why you should be suspicious every time you see one in a report. You will meet this again formally in
Session 2 as *skew*.
"""),
md("""
## 4 · Draw one picture

A single histogram tells you more than `describe()` ever will. A histogram chops the range into bins
and counts how many observations land in each.
"""),
code("""
fig, ax = plt.subplots(figsize=(8, 4))
sns.histplot(data=deposits, x="balance", bins=60, ax=ax)
ax.set_title("Account balances — almost everything is small, a few are enormous")
ax.set_xlabel("balance ($)")
plt.show()
"""),
md("""
That shape — a tall pile against the left wall and a long tail stretching right — is called
**right-skewed** (or positively skewed). It is the most common shape in money data of any kind:
balances, incomes, transaction sizes, claim amounts.

The picture explains the mean/median gap instantly, which is the general lesson: **plot first, then
compute.** A number can hide a shape; a shape cannot hide from a plot.
"""),
md("""
## 5 · Slicing: asking questions of subsets

Two operations do most of the work in pandas. First, selecting rows that meet a condition:
"""),
code("""
cds = deposits[deposits["product"] == "CD"]
print("CD accounts:", len(cds))
print(f"their mean balance: ${cds.balance.mean():,.0f}")
"""),
md("""
Second, `groupby` — "split into groups, compute something for each." This is the workhorse.
"""),
code("""
deposits.groupby("branch")["balance"].agg(["count", "mean", "median"]).round(0)
"""),
md("""
Read that as: *for each branch, give me the count, mean, and median balance.* Notice that within
every single branch the mean still sits well above the median — the skew is a property of how money
is distributed, not an artefact of mixing branches together.
"""),
md("""
## Your turn

Three exercises. Try each one before opening the solution underneath it — the struggle is the part
that makes it stick. If you are stuck for more than five minutes, open it; you are not being graded.

**Exercise 1.** How many accounts are in the Provo branch, and what is their median balance?
"""),
code("""
# your code here
"""),
sol("""
provo = deposits[deposits["branch"] == "Provo"]
print("Provo accounts:", len(provo))
print(f"median balance: ${provo.balance.median():,.0f}")
"""),
md("""
**Exercise 2.** Use `groupby` to find the mean `tenure_years` for each `product`. Which product has
the longest-tenured customers?
"""),
code("""
# your code here
"""),
sol("""
print(deposits.groupby("product")["tenure_years"].mean().round(2).sort_values(ascending=False))
# CDs tend to be held by longer-tenured customers -- they are a commitment product.
"""),
md("""
**Exercise 3.** Draw a histogram of `tenure_years`. Is it skewed the same way `balance` was?
"""),
code("""
# your code here
"""),
sol("""
fig, ax = plt.subplots(figsize=(8, 4))
sns.histplot(data=deposits, x="tenure_years", bins=40, ax=ax)
ax.set_title("Customer tenure")
plt.show()

print(f"mean {deposits.tenure_years.mean():.2f} vs median {deposits.tenure_years.median():.2f}")
# Also right-skewed, but far more mildly -- the mean/median gap is small.
# Skew is a matter of degree, not a yes/no property.
"""),
md("""
## What you did today

- Loaded a CSV, checked its shape, summarised it, and plotted it — the four moves you will repeat all term.
- Learned that rows are **observations**, columns are **variables**, and `n` is the row count.
- Met `x̄` (sample mean) and saw *why* the mean and median can disagree badly.
- Learned the habit that matters most: **plot before you conclude.**

**Next:** `02_shape_center_spread.ipynb` — naming the shapes and measuring the spread.
"""),
])

# =============================================================== 02
build("02_shape_center_spread.ipynb", "Shape, Center, Spread", [
md("""
# 02 · Shape, Center, Spread

**Session 2 · Thu Sep 17 · 1 hour (stats half)**

Any distribution can be described by three questions, and almost every descriptive statistic you
will meet is an answer to one of them:

1. **Shape** — what does it look like?
2. **Center** — where is the middle?
3. **Spread** — how spread out is it?

Get these three and you can describe any variable in any dataset in one sentence.
"""),
code(PRELUDE),
code("""
deposits = pd.read_csv(DATA / "branch_deposits.csv")
lending = pd.read_csv(DATA / "lending.csv")
"""),
md("""
## 1 · Center: three different "averages"

Three measures of center, and they answer different questions.
"""),
code("""
x = deposits["balance"]

print(f"mean   (x̄):  ${x.mean():>10,.0f}   <- add everything up, divide by n")
print(f"median:      ${x.median():>10,.0f}   <- sort, take the middle value")
print(f"mode (bin):  ${x.round(-3).mode()[0]:>10,.0f}   <- the most common value (rounded to $1k)")
"""),
md("""
**Which one should you use?**

| Use | When | Why |
|---|---|---|
| **Median** | Money, anything skewed | Unmoved by extreme values |
| **Mean** | Symmetric data; when you need totals | It is the only one where `mean × n = total` |
| **Mode** | Categories | "Most common product" makes sense; "mean product" does not |

The mean has one property the median lacks and it is the reason the mean dominates statistics:
`mean × n` recovers the **total**. Your bank cares about total deposits, so the mean is unavoidable
even when it is a poor description of a typical customer. Both facts are true at once, and a careful
analyst reports both numbers.

## 2 · Spread: how much do values vary?
"""),
code("""
print(f"range:              ${x.max() - x.min():>12,.0f}   (max - min; hostage to one outlier)")
print(f"IQR:                ${x.quantile(.75) - x.quantile(.25):>12,.0f}   (middle 50% -- robust)")
print(f"variance (σ²):      {x.var():>13,.0f}   (in dollars-SQUARED, uninterpretable)")
print(f"std deviation (σ):  ${x.std():>12,.0f}   (back in dollars -- interpretable)")
"""),
md("""
### Why variance exists at all

Variance is the average squared distance from the mean. Squared *dollars* are meaningless as a unit,
so why bother?

Because we need distances to be positive. Distances from the mean cancel out to exactly zero by
definition — that is what "mean" means. Squaring fixes the sign, and squares are mathematically far
better behaved than absolute values (they are smooth and differentiable, which matters enormously
once you get to machine learning and gradient descent).

Then we take the square root to return to dollars, and call it the **standard deviation**. So:

> **variance = the mathematically convenient one. standard deviation = the interpretable one.**

They carry identical information. Report `σ`; the machinery uses `σ²`.
"""),
code("""
# Proof that deviations cancel to zero -- this is why we square them.
deviations = x - x.mean()
print(f"sum of raw deviations:     {deviations.sum():>20,.6f}   <- zero (floating-point dust)")
print(f"sum of SQUARED deviations: {(deviations**2).sum():>20,.0f}   <- something to work with")
"""),
md("""
## 3 · Shape: learn to recognise these four

Shape is the one you assess by eye. Four shapes cover most of what you will meet.
"""),
code("""
fig, axes = plt.subplots(2, 2, figsize=(11, 7))

sns.histplot(rng.normal(100, 15, 3000), bins=45, ax=axes[0, 0], color="#3b6ea5")
axes[0, 0].set_title("Symmetric / bell-shaped\\nmean ≈ median  (heights, test scores)")

sns.histplot(rng.lognormal(3, .9, 3000), bins=45, ax=axes[0, 1], color="#a5533b")
axes[0, 1].set_title("Right-skewed\\nmean > median  (money, almost always)")

sns.histplot(6 - rng.lognormal(1, .5, 3000) / 3, bins=45, ax=axes[1, 0], color="#3b8f5a")
axes[1, 0].set_title("Left-skewed\\nmean < median  (age at death, exam ceilings)")

sns.histplot(np.concatenate([rng.normal(35, 6, 1500), rng.normal(70, 7, 1500)]),
             bins=45, ax=axes[1, 1], color="#6b4ea5")
axes[1, 1].set_title("Bimodal — TWO humps\\nyou are looking at two mixed populations")

plt.tight_layout(); plt.show()
"""),
md("""
### The one that should make you stop work

**Bimodal.** Two humps almost always means you have accidentally combined two different populations
— two products, two customer segments, two branches with different policies, or data from before and
after a process change.

Summarising a bimodal distribution with a single mean produces a number describing *nobody*. If the
two humps sit at 35 and 70, the mean lands near 52, where there is hardly any data at all.

When you see two humps, the correct next move is not to compute a statistic. It is to ask **"what
variable am I missing?"** — then split on it and describe each group separately.
"""),
md("""
## 4 · Skew, as a number

Your eye is good at skew, but you can also just measure it.
"""),
code("""
for col in ["balance", "tenure_years"]:
    s = deposits[col]
    print(f"{col:15s} skew = {s.skew():>6.2f}   mean/median = {s.mean()/s.median():.2f}x")

print()
print("rule of thumb:  |skew| < 0.5 roughly symmetric | 0.5-1 moderate | > 1 strong")
"""),
md("""
## Your turn

**Exercise 1.** For `annual_income` in the `lending` data: report mean, median, and skew, and say in
one sentence which measure of center you would put in a report and why.
"""),
code("""
# your code here
"""),
sol("""
inc = lending["annual_income"]
print(f"mean   ${inc.mean():,.0f}")
print(f"median ${inc.median():,.0f}")
print(f"skew   {inc.skew():.2f}")
# Mildly right-skewed -- mean and median are close, so either works. I'd report the
# median for "a typical applicant" and the mean if I needed to recover total income.
"""),
md("""
**Exercise 2.** Plot `credit_score` split by `applicant_group` (hint: `hue="applicant_group"`).
What do you see, and what question does it raise?
"""),
code("""
# your code here
"""),
sol("""
fig, ax = plt.subplots(figsize=(9, 4.5))
sns.histplot(data=lending, x="credit_score", hue="applicant_group",
             bins=45, alpha=.55, ax=ax)
ax.set_title("Credit score by applicant group")
plt.show()

print(lending.groupby("applicant_group")["credit_score"].agg(["count","mean","median"]).round(1))

# Group B's distribution sits visibly to the LEFT -- lower scores on average.
#
# The question this raises is the whole of PhDAI 832: is that difference a fact about
# creditworthiness, or a fact about how the historical data was generated? A model trained
# on this data will produce different outcomes by group WITHOUT ever using group as an
# input, because the features it does use carry the disparity. That is exactly what
# "historical bias" means, and you cannot fix it by deleting the group column.
"""),
md("""
## What you did today

- Three centers (mean/median/mode) and when each is the honest choice.
- Why variance is squared, and why you report the standard deviation instead.
- Four shapes by sight — and why **bimodal** means stop and find your missing variable.
- Saw a group disparity in real-shaped data, which is the bridge into your ethics course.

**Next:** `03_distribution_zoo.ipynb` — generating distributions yourself until the shapes are obvious.
"""),
])
